### ISSUE TITLE
Error: repository not enabled for code scanning

### ISSUE THREAD

**Issue by Karim-53** [facebook/pyre-action#4]
Hi,

I am trying to run Pyre on a private repo. 
But I get this error: `Error: repository not enabled for code scanning` 

I tried to enable code scanning, but it is not that easy: 
![image](https://user-images.githubusercontent.com/33978275/209290757-f20b2fdf-aafc-4059-a2a9-28ca32c89af4.png)

Is `Run github/codeql-action/upload-sarif@v2` really mandatory to check the python code style?

**Comment by scherersebastian** [comment]
Hi @Karim-53 
you can fork this repo and remove the Sarif specific steps from https://github.com/facebook/pyre-action/blob/main/action.yml
```
    - name: Run Pyre
      run: |
        cd "$REPO_DIR" || exit 1
        pyre --noninteractive --output=sarif check > sarif.json
      shell: bash
      env:
        REPO_DIR: ${{inputs.repo-directory}}

    - name: Saving results in SARIF
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: SARIF Results
        path: ${{inputs.repo-directory}}/sarif.json
        if-no-files-found: ignore

    - name: Upload SARIF Results
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{inputs.repo-directory}}/sarif.json
```
And configure a different pyre / pysa reporting format or just output the sarif.json to the console.
